---
- name: "Set TLS 1.2"
  win_shell: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"

- name: "Set execution policy"
  win_shell: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force

- name: Ensure cUrl is installed.
  win_chocolatey:
     name: curl
     state: present
     
- name: Ensure Jenkins is installed.
  win_chocolatey:
     name: jenkins
     state: present
  register: jenkins_install_package_win

- name: "Reset execution policy"
  win_shell: Set-ExecutionPolicy RemoteSigned -Scope Process -Force
